### ISSUE TITLE
Unable to disable registration

### ISSUE THREAD

**Issue by nzrunner** [taPMeppeSols/grav-theme-upmorph-online-soon#1]
I have turned on registration within the Theme. I now wish to turn it off as I do not want to use it.

How do I disable it, as when I delete the registration sections and Save the theme, the registration remains?

**Comment by tapmeppe** [comment]
Hello there,
I was able to reproduce the problem in the most recent version of GRAV. Quite peculiar.
I have added a status check in the new version of the theme to simplify the respective deactivation of the registration - & social networks modules.

Greetings.
