### ISSUE TITLE
unexpected )

### ISSUE THREAD

**Issue by goeldicom** [taPMeppeSols/grav-theme-upmorph-online-soon#3]
I try to install upmorph-online-soon. It doesn't matter if I install it by bin/gpm install or via the install button in the admin panel.

I immediately get this error on line 261 of upmorph-online-soon.php:

`syntax error, unexpected ')'`

This happens upon installation (theme is not activated yet).

My versions:

grav v1.6.26
admin v1.9.15
php 7.2.24
apache 2.4.29

Server is Ubuntu 18.04.4 LTS

**Comment by mentarus** [comment]
Saw this too, just remove the trailing comma on line 260

**Comment by tapmeppe** [comment]
Hello there.
The trailing comma will be removed in the next version.

Greetings.
